### ISSUE TITLE
Merging does not work with Playwright 1.32.0

### ISSUE THREAD

**Issue by MindaugasMateika** [Rippling/playwright-merge-html-reports#2]
Merging reports generated with Playwright 1.32.0 produces an error if there's trace folder in the report.

```
Failed to merge reports: {"errno":-45,"code":"ENOTSUP","syscall":"copyfile","path":"/Users/<username>/web-e2e-tests/playwright-report-1/trace/assets","dest":"/Users/<username>/web-e2e-tests/playwright-report/trace/assets"}
```

Trace folder structure within html report has changed with 1.32.0 release and now contains sub-folder as well.

**Comment by costa-collibra** [comment]
I was just about to log this issue too
